-- AlterTable
ALTER TABLE "User" ADD COLUMN     "billingPeriodStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "creditsLimit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "creditsUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "whatsappLimit" INTEGER NOT NULL DEFAULT 1;
